spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/babycentral?useSSL=false"
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      maxFileSize: 5MB

server:
  port: 9001
  use-forward-headers: true

app:
  companyName: Archangel Design