spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/babycentral?useSSL=false"
    username: ${BABY_CENTRAL_DB_USER}
    password: ${BABY_CENTRAL_DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9001
  use-forward-headers: true

app:
  companyName: Archangel Design

one-signal:
  appId: ${BABY_CENTRAL_ONE_SIGNAL_APP_ID}
  authorizationId: ${BABY_CENTRAL_ONE_SIGNAL_AUTH_ID}